
apiVersion: v1
kind: Service
metadata:
  name: identityservice
spec:
  selector:
    app: identityservice
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
spec:
  selector:
    matchLabels:
      app: identityservice
  replicas: 1
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - name: server
          env:
            - name: DB_NAME
              value: spacex_agency_system
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: password
          image: maniabraun/identityservice
          ports:
            - name: http
              containerPort: 8081




