
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  selector:
    matchLabels:
      app: authservice
  replicas: 1
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: server
          image: maniabraun/authentityservice
          ports:
            - name: http
              containerPort: 8080




